"""initial schema

Revision ID: 37aef055a863
Revises: 
Create Date: 2026-03-03 00:29:44.759624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37aef055a863'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa_config', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_empresa_config_ultimo_garcom_id', 'garcons', ['ultimo_garcom_id'], ['id'])

    with op.batch_alter_table('enderecos_estoque', schema=None) as batch_op:
        batch_op.alter_column('codigo_localizacao',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=60),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'ativo'"))
        batch_op.create_foreign_key('fk_enderecos_estoque_estoque_id', 'estoques', ['estoque_id'], ['id'])

    with op.batch_alter_table('estoques', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_estoques_criado_em'), ['criado_em'], unique=False)
        batch_op.create_foreign_key('fk_estoques_endereco_destino_id', 'enderecos_estoque', ['endereco_destino_id'], ['id'])
        batch_op.create_foreign_key('fk_estoques_endereco_origem_id', 'enderecos_estoque', ['endereco_origem_id'], ['id'])

    with op.batch_alter_table('fornecedores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fornecedores_criado_em'), ['criado_em'], unique=False)

    with op.batch_alter_table('funcionarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_funcionarios_email'), ['email'], unique=True)

    with op.batch_alter_table('garcons', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_garcons_funcionario_id', 'funcionarios', ['funcionario_id'], ['id'])

    with op.batch_alter_table('movimentacoes', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_movimentacoes_endereco_destino_id', 'enderecos_estoque', ['endereco_destino_id'], ['id'])
        batch_op.create_foreign_key('fk_movimentacoes_endereco_origem_id', 'enderecos_estoque', ['endereco_origem_id'], ['id'])

    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pedidos_status'), ['status'], unique=False)
        batch_op.create_foreign_key('fk_pedidos_garcom_id', 'garcons', ['garcom_id'], ['id'])

    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.alter_column('status_disponibilidade',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'disponivel_venda'"))
        batch_op.create_index(batch_op.f('ix_produtos_codigo'), ['codigo'], unique=True)
        batch_op.create_foreign_key('fk_produtos_endereco_id', 'enderecos_estoque', ['endereco_id'], ['id'])
        batch_op.create_foreign_key('fk_produtos_fornecedor_id', 'fornecedores', ['fornecedor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_constraint('fk_produtos_fornecedor_id', type_='foreignkey')
        batch_op.drop_constraint('fk_produtos_endereco_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_produtos_codigo'))
        batch_op.alter_column('status_disponibilidade',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'disponivel_venda'"))

    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_constraint('fk_pedidos_garcom_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_pedidos_status'))

    with op.batch_alter_table('movimentacoes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_movimentacoes_endereco_origem_id', type_='foreignkey')
        batch_op.drop_constraint('fk_movimentacoes_endereco_destino_id', type_='foreignkey')

    with op.batch_alter_table('garcons', schema=None) as batch_op:
        batch_op.drop_constraint('fk_garcons_funcionario_id', type_='foreignkey')

    with op.batch_alter_table('funcionarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_funcionarios_email'))

    with op.batch_alter_table('fornecedores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fornecedores_criado_em'))

    with op.batch_alter_table('estoques', schema=None) as batch_op:
        batch_op.drop_constraint('fk_estoques_endereco_origem_id', type_='foreignkey')
        batch_op.drop_constraint('fk_estoques_endereco_destino_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_estoques_criado_em'))

    with op.batch_alter_table('enderecos_estoque', schema=None) as batch_op:
        batch_op.drop_constraint('fk_enderecos_estoque_estoque_id', type_='foreignkey')
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'ativo'"))
        batch_op.alter_column('codigo_localizacao',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=40),
               existing_nullable=True)

    with op.batch_alter_table('empresa_config', schema=None) as batch_op:
        batch_op.drop_constraint('fk_empresa_config_ultimo_garcom_id', type_='foreignkey')

    # ### end Alembic commands ###
